config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount GoodJob::Engine => 'good_job'
  get 'operators/show'
  localized do
    get  'sign_in', to: 'sessions#new'
    post 'sign_in', to: 'sessions#create'
    get  'sign_up', to: 'registrations#new'
    post 'sign_up', to: 'registrations#create'
    get 'admin', to: 'admin#show'
    namespace :admin do
      resource :game_data_import, only: %i[create]
      resource :channels_import, only: %i[create]
      resources :clear_jobs, controller: 'extract_clear_data_from_video_jobs'
      resources :videos_imports, only: %i[new create]
      resource :clear_from_job, only: %i[new]
      resources :users, only: %i[index update edit show]
      resources :clear_test_cases, only: %i[index show update destroy]
      resources :clear_test_runs, only: %i[new create show destroy update] do
        resources :clear_test_results, only: %i[index show update]
      end
      resource :extract_clear_result_export, only: %i[show]
      resources :extract_clear_result_imports, only: %i[create]
    end
    resources :sessions, only: %i[index show destroy]
    resource  :password, only: %i[edit update]
    resource  :username, only: %i[edit update]
    namespace :identity do
      resource :email,              only: %i[edit update]
      resource :email_verification, only: %i[show create]
      resource :password_reset,     only: %i[new edit create update]
    end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root 'home#index'
    resources :healthz, only: %i[index]

    resources :channels
    namespace :clears do
      resource :filters, only: %i[show]
      resource :stage_select, only: %i[show]
      resource :operators_select, only: %i[show]
      resource :used_operator
    end
    resources :clears do
      resources :used_operators
      resource :like, only: %i[create destroy], controller: 'clears/likes'
      resource :report, only: %i[create destroy], controller: 'clears/reports'
      resource :verification, only: %i[edit update create destroy new], controller: 'clears/verifications'
      namespace :verification do
        resources :used_operators, only: %i[edit update], controller: '/clears/verifications/used_operators'
      end
    end
    resources :operators
  end
end
# rubocop:enable Metrics/BlockLength

app/controllers/admin/clear_test_results_controller.rb
# frozen_string_literal: true

class Admin::ClearTestResultsController < ApplicationController
  load_resource :clear_test_run, class: 'ClearImage::TestRun'

  def index
    @clear_test_run.latest_size = params.dig(:clear_test_run, :latest_size) || 5
    @clear_test_results = @clear_test_run.test_results
    ClearImage::TestResult.preload_test_case(@clear_test_results)
  end

  def show
    get_clear_test_result
    preload_operators_data
  end

  def update
    get_clear_test_result
    @clear_test_result.configuration = params[:clear_test_result][:configuration].permit!.to_h
    @clear_test_result.rerun!
    redirect_to admin_clear_test_run_clear_test_result_path(@clear_test_run, @clear_test_result.test_case_id)
  end

  private

  def preload_operators_data
    I18n.with_locale(@clear_test_result.language) do
      Operator.build_translations_cache(Operator.where(id: @clear_test_result.all_operators.pluck(:operator_id)))
    end
    ActiveRecord::Associations::Preloader.new(
      records: @clear_test_result.all_operators,
      associations: [:operator]
    ).call
  end

  def get_clear_test_result
    @clear_test_result = ClearImage::TestResult.new(test_case_id: params[:id], test_run_id: @clear_test_run.id)
  end
end

app/views/admin/clear_test_results/index.html.erb
<div class="flex justify-between">
  <%= link_to t('.view_test_run'), admin_clear_test_run_path(@clear_test_run), class: 'btn btn-neutral w-fit mb-2' %>
  <%= button_to t('.destroy_test_run'), admin_clear_test_run_path(@clear_test_run), method: :delete, class: 'btn btn-error w-fit mb-2' %>
</div>
<div class="flex justify-between">
  <% if @clear_test_run.prev_test_run_id %>
    <%= link_to admin_clear_test_run_clear_test_results_path(@clear_test_run.prev_test_run_id), class: 'btn' do %>
      <%= heroicon 'arrow-left' %>
    <% end %>
  <% else %>
    <div></div>
  <% end %>
  <% if @clear_test_run.next_test_run_id %>
    <%= link_to admin_clear_test_run_clear_test_results_path(@clear_test_run.next_test_run_id), class: 'btn' do %>
      <%= heroicon 'arrow-right' %>
    <% end %>
  <% else %>
    <div></div>
  <% end %>
</div>
<section>
  <div class="card bg-base-200 ">
    <h2 class="text-2xl mb-2"> TR: <%= @clear_test_run.name || @clear_test_run.id %></h2>
    <div class="card-body p-2">
      <%= render Admin::ClearImage::TestRunConfigurationComponent.new(test_run: @clear_test_run) %>
    </div>
  </div>
  <div class="card bg-base-200 mt-4">
    <div class="card-body">
      <%= turbo_frame_tag @clear_test_run do  %>
        <%= simple_form_for @clear_test_run, as: :clear_test_run, url: admin_clear_test_run_path(@clear_test_run), data: { **stimulus(:click_other) } do |f| %>
          <%= f.input :latest_size, input_html: { data: { **stimulus_attrs(:click_other, actions: { 'focusout': 'clickOther' }) } } %>
          <%= f.label :correct_ratio, class: 'simple_form__label' %>
          <div class="outline w-fit outline-neutral rounded p-2">
            <%= render Admin::ClearImage::TestRunCorrectRatioComponent.new(
            correct_ratio: @clear_test_results.map(&:correct_ratio).compact.sum.round(2),
            max_latest_correct_ratio: @clear_test_results.map(&:max_latest_correct_ratio).compact.sum.round(2),
            correct_name_ratio: 
              (@clear_test_results.map(&:correct_name_op_count).sum.to_f / @clear_test_results.map(&:total_op_count).sum).round(2) * 100
          ) %>
          </div>
          <%= content_tag :button, class: 'hidden', data: { **stimulus_attrs(:click_other, target: 'clickable'), turbo_frame: '_top' },
        formmethod: :get, formaction: admin_clear_test_run_clear_test_results_url(@clear_test_run) do %>
          <% end %>
          <%= f.input :note, input_html: { class: 'w-full' } %>
          <%= f.button :submit, class: 'self-end mt-2' %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="grid grid-cols-5 gap-2">
    <% @clear_test_results.each do |test_result| %>
      <%= link_to admin_clear_test_run_clear_test_result_path(@clear_test_run, test_result.test_case_id) do %>
        <article class="card bg-base-200 mt-2">
          <div class="card-body">
            <div class="flex justify-start space-x-2 items-center">
              <%= render Admin::ClearImage::TestResultSummaryComponent.new(test_result: test_result) %>
            </div>
            <%= render Admin::ClearImage::TestRunCorrectRatioComponent.new(test_result: test_result) %>
          </div>
        </article>
      <% end %>
    <% end %>
  </div>
</section>

app/views/admin/clear_test_results/show.html.erb
<img id="image_frame" class="hidden fixed z-50 m-auto top-[50%] left-[50%]">
<%= link_to t('.view_other_results'), admin_clear_test_run_clear_test_results_path(@clear_test_run), class: 'btn btn-neutral w-fit' %>
<section class="test-result">
  <div class="flex justify-between">
    <% if (prev_test_run_id = @clear_test_run.prev_test_run_id(test_case_id: @clear_test_result.test_case_id)) %>
      <%= link_to admin_clear_test_run_clear_test_result_path(prev_test_run_id, @clear_test_result.test_case_id), class: 'btn' do %>
        <%= heroicon 'arrow-left' %>
      <% end %>
    <% else %>
      <div></div>
    <% end %>
    <% if (next_test_run_id = @clear_test_run.next_test_run_id(test_case_id: @clear_test_result.test_case_id))%>
      <%= link_to admin_clear_test_run_clear_test_result_path(next_test_run_id, @clear_test_result.test_case_id), class: 'btn' do %>
        <%= heroicon 'arrow-right' %>
      <% end %>
    <% else %>
      <div></div>
    <% end %>
  </div>
  <%= render Admin::ClearImage::TestRunConfigurationComponent.new(
    configuration: { @clear_test_result.language => (@clear_test_result.configuration || @clear_test_run.configuration[@clear_test_result.language.to_s])}
  ) %>
  <section class="space-y-1">
    <h3 class="text-xl"><%= t('.summary') %></h3>
    <div class="flex items-center space-x-2">
      <%= render Admin::ClearImage::TestResultSummaryComponent.new(test_result: @clear_test_result) %>
    </div>
    <% if @clear_test_result.failed? %>
      <div class="alert alert-error">
        <%= @clear_test_result.error_message  %>
      </div>
    <% end %>
    <div>
      <%= render Admin::ClearImage::TestRunCorrectRatioComponent.new(test_result: @clear_test_result) %>
    </div>
    <div class="divider"></div>
    <%= render Admin::ImageComponent.new(path: @clear_test_result.clear_image_src, width: '500px') %>
  </section>
  <div class="divider"></div>
  <section class="mt-2">
    <h3 class="text-xl"> <%= t('.artifact_images') %></h3>
    <div class="flex space-x-2">
      <% @clear_test_result.artifact_image_srcs.each do |src| %>
        <%= render Admin::ImageComponent.new(path: src, width: '200px') %>
      <% end %>
    </div>
  </section>
  <section class="mt-2">
    <h3 class="text-xl"> <%= t('.name_box_images') %></h3>
    <div class="flex flex-wrap gap-1">
      <% @clear_test_result.name_box_image_srcs.each do |src| %>
        <div class="p-2 border border-neutral">
          <%= render Admin::ImageComponent.new(path: src, width: '100px') %>
        </div>
      <% end %>
    </div>
  </section>
  <section>
    <h3>View logs</h3>
    <% @clear_test_result.log_sections&.each do |log_section| %>
      <%= content_tag :details,  class: 'collapse overflow-auto' do%>
        <%= content_tag :summary, class: 'collapse-title !list-item ' do %>
          <%= log_section.split("\n").first %>
        <% end %>
        <div class="whitespace-pre h-96 overflow-auto">
          <p>
            <%= log_section %>
          </p>
        </div>
      <% end %>
    <% end %>
  </section>
  <div class="mt-2">
    <section class="card bg-base-200">
      <div class="card-body">
        <h3 class="card-title text-warning"> <%= "#{t(".failed_operators")}: #{@clear_test_result.failed_operators.size}" %></h3>
        <div class="flex flex-wrap gap-2">
          <% @clear_test_result.failed_operators.each do |(expected_used_operator, received_used_operator)| %>
            <div class="flex space-x-2">
              <article
                class="operators__card  card w-full sm:w-fit "
                data-operator-id="<%= received_used_operator.operator_id %>"
              >
                <div class="card-body shadow-xl bg-base-100 rounded p-3 sm:w-fit">
                  <% I18n.with_locale(@clear_test_result.language) do %>
                    <h3 class="text-base card-title absolute -bottom-1"> <%= received_used_operator.name %> </h3>
                  <% end %>
                  <div class="flex gap-2">
                    <div class="flex flex-col items-center space-y-1">
                      <%= image_tag received_used_operator.avatar, class: "w-24", alt: received_used_operator.name %>
                    </div>
                    <div class="grid grid-cols-2 grid-rows-2 gap-x-2 text-base sm:text-xl">
                      <%= vite_image_tag received_used_operator.elite_image_url, class: "w-8 " %>
                      <% if expected_used_operator.elite != received_used_operator.elite %>
                        <%= vite_image_tag expected_used_operator.elite_image_url, class: "w-8 " %>
                      <% else %>
                        <span></span>
                      <% end %>
                      <span class="mt-1 "><%= received_used_operator.level %></span>
                      <span class="mt-1 "><%= (expected_used_operator.level if received_used_operator.level != expected_used_operator.level)  %></span>
                      <%= image_tag received_used_operator.skill_image_url, class: "w-7" %>
                      <% if received_used_operator.skill != expected_used_operator.skill %>
                        <%= image_tag (expected_used_operator.skill_image_url ), class: "w-7" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </article>
            </div>
          <% end %>
        </div>
      </div>
    </section>
  </div>
  <div>
    <% {
      missing_operators: [@clear_test_result.missing_operators, 'error'],
      passed_operators: [@clear_test_result.passed_operators, 'success'],
      extra_operators: [@clear_test_result.extra_operators, 'extra'],
    }.each do |key, (operators, color_key)| %>
      <section class="card bg-base-200 mt-2">
        <div class="card-body">
          <h3 class="card-title text-<%= color_key %>"> <%= "#{t(".#{key}")}: #{operators.size}" %></h3>
          <div class="flex flex-wrap gap-2">
            <% operators.each do |used_operator| %>
              <% I18n.with_locale(@clear_test_result.language) do %>
                <%= render Clears::UsedOperatorComponent.new(used_operator: used_operator, editable: false) %>
              <% end %>
            <% end %>
          </div>
        </div>
      </section>
    <% end %>
  </div>
  <div class="flex justify-between mt-2">
    <%= simple_form_for :clear_test_result, method: :patch,
      url: admin_clear_test_run_clear_test_result_path(@clear_test_run, @clear_test_result.test_case_id) do |f| %>
      <%= f.input :test_run_id, as: :hidden, input_html: { value: @clear_test_result.test_run_id }  %>
      <%= f.simple_fields_for :configuration, ClearImage::Configuration.new(@clear_test_result.configuration || {}) do |conf_f|  %>
        <% conf_f.object.attributes.each_key do |attr| %>
          <%= conf_f.input attr %>
        <% end %>
      <% end %>
      <%= f.button :submit, t('.rerun') %>
    <% end %>
    <%= button_to admin_clear_test_case_path(@clear_test_result.test_case_id), method: :PATCH, class: 'btn btn-warning' do |f|%>
      <%= simple_fields_for ClearImage::TestCase.new  do |f| %>
        <%= f.input :test_run_id, as: :hidden, input_html: { value: @clear_test_result.test_run_id }  %>
        <%= t('.update_test_case') %>
      <% end %>
    <% end %>
  </div>
</section>