config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount GoodJob::Engine => 'good_job'
  get 'operators/show'
  localized do
    get  'sign_in', to: 'sessions#new'
    post 'sign_in', to: 'sessions#create'
    get  'sign_up', to: 'registrations#new'
    post 'sign_up', to: 'registrations#create'
    get 'admin', to: 'admin#show'
    namespace :admin do
      resource :game_data_import, only: %i[create]
      resource :channels_import, only: %i[create]
      resources :clear_jobs, controller: 'extract_clear_data_from_video_jobs'
      resources :videos_imports, only: %i[new create]
      resource :clear_from_job, only: %i[new]
      resources :users, only: %i[index update edit show]
      resources :clear_test_cases, only: %i[index show update destroy]
      resources :clear_test_runs, only: %i[new create show destroy update] do
        resources :clear_test_results, only: %i[index show update]
      end
      resource :extract_clear_result_export, only: %i[show]
      resources :extract_clear_result_imports, only: %i[create]
    end
    resources :sessions, only: %i[index show destroy]
    resource  :password, only: %i[edit update]
    resource  :username, only: %i[edit update]
    namespace :identity do
      resource :email,              only: %i[edit update]
      resource :email_verification, only: %i[show create]
      resource :password_reset,     only: %i[new edit create update]
    end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root 'home#index'
    resources :healthz, only: %i[index]

    resources :channels
    namespace :clears do
      resource :filters, only: %i[show]
      resource :stage_select, only: %i[show]
      resource :operators_select, only: %i[show]
      resource :used_operator
    end
    resources :clears do
      resources :used_operators
      resource :like, only: %i[create destroy], controller: 'clears/likes'
      resource :report, only: %i[create destroy], controller: 'clears/reports'
      resource :verification, only: %i[edit update create destroy new], controller: 'clears/verifications'
      namespace :verification do
        resources :used_operators, only: %i[edit update], controller: '/clears/verifications/used_operators'
      end
    end
    resources :operators
  end
end
# rubocop:enable Metrics/BlockLength

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  include ClearFilterable
  skip_before_action :authenticate!

  def index
    delete_clear_spec_session
    @clear_spec = Clear.new
    @newest_clears = Clear.not_rejected.includes(:channel, :likes, stage: :stageable,
                                                                   used_operators: :operator).order(created_at: :desc).limit(6)
    @trending_clears = Clear.preload(:channel, :likes, stage: :stageable)
                            .not_rejected
                            .joins(:likes)
                            .where(likes: { created_at: 1.day.ago... })
                            .group(:id)
                            .select('clears.*',
                                    'count(clears.id) as likes_count')
                            .order(likes_count: :desc).limit(6)
    Operator.build_translations_cache(Operator.from_clear_ids((@trending_clears + @newest_clears).map(&:id)))
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/index.html.erb
<% set_meta_tags(title: t('meta.home.title'), reverse: false) %>
<% description t('meta.home.description') %>
<div class="md:flex flex-row gap-12">
  <!-- Consider using defer loading turbo frames for each component -->
  <div class="grid grid-cols-1 sm:grid-cols-2 grow gap-6 sm:gap-12 basis-0">
    <div  class=" sm:col-span-2">
      <section>
        <h2 class="text-2xl">
          <%= t('.title_1') %>
        </h2>
        <div class="p-2"></div>
        <p>
          <%= t('.desc_1.first_line') %>
        </p>
        <section class="space-y-2">
          <%= simple_form_for @clear_spec, method: :get, html: {
          id: "clears__form",
          data: {
            turbo_stream: "true",
          },
          class: 'flex flex-col'
        } do |f| %>
            <%= content_tag :div, class: 'block' do %>
              <%= render Clears::StageSelectComponent.new(form: f, simple: true, stage_label: t('.desc_1.choose_stage')) %>
            <% end %>
            <div id="clears__form__operators_fields" class="hidden">
            </div>
          <% end %>
          <div id="home_operators__list" class="flex flex-wrap self-center items-center justify-items-end">
            <span class="label w-full sm:w-fit"><%= t('.desc_1.choose_your_favorite_operators') %></span>
            <% @clear_spec.used_operators.each do |used_operator| %>
              <%= render Clears::UsedOperatorMiniComponent.new(used_operator: used_operator) %>
            <% end %>
            <%= render Clears::Form::NewOperatorButtonComponent.new(squad: @clear_spec.squad, create: true) %>
          </div>
          <span class="label"><%= t('.desc_1.click_the_button') %> </span>
          <div>
            <button form="clears__form" class="btn btn-primary btn-sm" type="submit">
              <%= t(:search) %>
            </button>
          </div>
        </section>
      </section>
      <section>
        <div class="divider"></div>
        <h2 class="text-2xl">
          <%= t('.title_2') %>
        </h2>
        <div class="p-2"></div>
        <div class="flex flex-col sm:flex-row">
          <span>
            Just <%= link_to t(:sign_in), sign_in_path, class: 'btn btn-outline btn-sm sm:mx-1' %> <%= t('.desc_2') %>:
          </span>
          <%= render Clears::NewBtnComponent.new %>
        </div>
      </section>
    </div>
    <div class="sm:col-span-2">
      <div class="divider w-full"></div>
      <%= render Home::HeroComponent.new(
        stageables: Event.latest,
        title: t('.latest_events')
      ) %>
    </div>
    <%= render Home::HeroComponent.new(
      stageables: Episode.latest,
      title: t('.latest_episode')
    ) %>
    <%= render Home::HeroComponent.new(
      stageables: Annihilation.latest,
      title: t('.latest_annihilation'),
      remote_image: true
    ) %>
  </div>
  <div class="md:max-w-[25%]">
    <% [
        [t('.trending_clears'), @trending_clears],
        [t('.latest_clears'), @newest_clears]
      ].each do |(title, clears)| %>
      <%= (render Clears::AsideComponent.new(
        clears: clears,
        title: title
      ) if clears.size > 0) %>
    <% end %>
  </div>
</div>