config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount GoodJob::Engine => 'good_job'
  get 'operators/show'
  localized do
    get  'sign_in', to: 'sessions#new'
    post 'sign_in', to: 'sessions#create'
    get  'sign_up', to: 'registrations#new'
    post 'sign_up', to: 'registrations#create'
    get 'admin', to: 'admin#show'
    namespace :admin do
      resource :game_data_import, only: %i[create]
      resource :channels_import, only: %i[create]
      resources :clear_jobs, controller: 'extract_clear_data_from_video_jobs'
      resources :videos_imports, only: %i[new create]
      resource :clear_from_job, only: %i[new]
      resources :users, only: %i[index update edit show]
      resources :clear_test_cases, only: %i[index show update destroy]
      resources :clear_test_runs, only: %i[new create show destroy update] do
        resources :clear_test_results, only: %i[index show update]
      end
      resource :extract_clear_result_export, only: %i[show]
      resources :extract_clear_result_imports, only: %i[create]
    end
    resources :sessions, only: %i[index show destroy]
    resource  :password, only: %i[edit update]
    resource  :username, only: %i[edit update]
    namespace :identity do
      resource :email,              only: %i[edit update]
      resource :email_verification, only: %i[show create]
      resource :password_reset,     only: %i[new edit create update]
    end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root 'home#index'
    resources :healthz, only: %i[index]

    resources :channels
    namespace :clears do
      resource :filters, only: %i[show]
      resource :stage_select, only: %i[show]
      resource :operators_select, only: %i[show]
      resource :used_operator
    end
    resources :clears do
      resources :used_operators
      resource :like, only: %i[create destroy], controller: 'clears/likes'
      resource :report, only: %i[create destroy], controller: 'clears/reports'
      resource :verification, only: %i[edit update create destroy new], controller: 'clears/verifications'
      namespace :verification do
        resources :used_operators, only: %i[edit update], controller: '/clears/verifications/used_operators'
      end
    end
    resources :operators
  end
end
# rubocop:enable Metrics/BlockLength

app/models/clear.rb
class Clear < ApplicationRecord
  include Dry::Monads[:result]
  include Clear::HardTaggable
  include Clear::Likeable
  include Reportable
  include Squadable
  include StageSpecifiable
  include Youtubeable
  include Duplicatable
  include Verifiable
  include Testable
  belongs_to :submitter, class_name: 'User'
  belongs_to :stage
  belongs_to :channel, optional: true

  scope :submitted_by, ->(user) { where(submitter_id: user.id) }

  delegate :event?, to: :stage, allow_nil: true

  normalizes :link, with: ->(value) { Video.new(value).to_url(normalized: true) || value }

  validate :valid_link
  validates :link, uniqueness: { conditions: ->(clear) { where(stage_id: clear.stage_ids) } }
  validates :name, length: { maximum: 255 }

  after_create :mark_job_as_clear_created
  after_commit :assign_channel, if: :trigger_assign_channel

  # considering separate spec logic from model
  attr_accessor :job_id, :self_only, :favorited, :trigger_assign_channel, :use_for_test_case

  def submitted_by?(user = Current.user)
    submitter == user
  end

  def preload_operators(with_verification: false)
    return unless persisted?

    nested_associations =
      if with_verification
        %i[operator verification]
      else
        [:operator]
      end

    ActiveRecord::Associations::Preloader.new(
      records: [self],
      associations: [used_operators: nested_associations]
    ).call
    Operator.build_translations_cache(Operator.from_clear_ids([id]))
    self
  end

  def valid_link
    return if (video = Video.new(link)).valid?

    errors.import(video.errors.where(:url).first, attribute: :link)
  end

  def mark_job_as_clear_created
    return if job_id.blank?

    job = ExtractClearDataFromVideoJob.find_by(id: job_id)
    job&.mark_clear_created! if job&.may_mark_clear_created?
  end

  def created_by_trusted_users?
    submitter.verifier? || submitter.admin?
  end

  def assign_channel
    # only run for admin?, run job at end of day/manually to insert channel info for all pending videos?
    return if previously_new_record? && channel.present?
    return unless saved_change_to_link?

    Clears::AssignChannelJob.perform_later(id, link)
  end
end

app/models/clear/hard_tag_list.rb
# frozen_string_literal: true

class Clear::HardTagList
  include Dry::Monads[:result, :do]
  VALID_TAGS = [
    LOW_END = 'Low-end',
    HIGH_END = 'High-end',
    NO_6_STARS = 'No-6-stars',
    ONLY_3_STARS = 'Only-3-stars'
  ].freeze
  attr_reader :value

  def initialize(value)
    @value = value
  end

  def add_tags(tags)
    tags = tags.uniq
    valid_tags = yield validate_tags(tags)

    Success((value + valid_tags).uniq)
  end

  def remove_tags(tags)
    Success((value - tags).uniq)
  end

  private

  def validate_tags(tags)
    if (invalid_tags = tags - VALID_TAGS).present?
      Failure("Not valid tags: #{invalid_tags.join(', ')} ")
    else
      Success(tags)
    end
  end
end

app/models/clear/specification.rb
# frozen_string_literal: true

class Clear::Specification
  include SimpleFormable
  extend Dry::Initializer

  option :stageable_id, optional: true, type: ::Types::Params::String
  option :stage_id, optional: true, type: ::Types::Params::Integer
  option :operator_id, optional: true, type: ::Types::Params::Integer
  option :challenge_mode, optional: true, type: ::Types::Params::Bool
  option :used_operators_attributes, optional: true, default: -> { {} }

  def used_operators
    @used_operators ||= used_operators_attributes.values.map { |attrs| UsedOperator.new(attrs) }
  end

  def stageable
    GlobalID::Locator.locate(stageable_id)
  end

  def stage_id
    stageable.is_a?(Annihilation) ? stageable.stages.first.id : super
  end

  def stage
    Stage.find_by(id: stage_id)
  end

  def used_operators_attributes=
    nil
  end
end

app/models/clear/test_case.rb
# frozen_string_literal: true

class Clear::TestCase < ApplicationRecord
  self.table_name = 'clear_test_cases'

  def self.enabled?
    Rails.env.local?
  end

  def video
    @video ||= Video.new(video_url)
  end

  belongs_to :clear
end

app/models/clear/test_result.rb
class Clear::TestResult
  include ActiveModel::Model
  include ActiveModel::Attributes
  include Presentable

  DATA_FILENAME = 'data.json'
  STATUSES = [
    PASSED = :passed,
    FAILED = :failed,
    COMPUTING = :computing,
    PENDING = :pending
  ]

  attribute :test_case_id, :integer
  attribute :test_run_id, :integer
  attribute :test_run
  attr_reader :data
  attr_writer :latest_test_runs, :test_case

  def self.preload_test_case(test_results)
    test_run = test_results.first.test_run
    case_to_result = test_results.index_by(&:test_case_id)
    test_run.test_cases.each do |test_case|
      case_to_result[test_case.id].test_case = test_case
    end
  end

  STATUSES.each do |status|
    define_method("#{status}?") do
      self.status == status.to_s
    end
  end

  def initialize(attributes = {})
    super
    self.test_run_id = test_run.id if attributes[:test_run]
    @data = {}
    read_from_file
  end

  def has_started?
    data_path.exist?
  end

  def status
    data[:status] || PENDING
  end

  def language
    data[:language]&.to_sym
  end

  def used_operators_data
    data[:used_operators_data] || []
  end

  def test_case_operator_data
    test_case.used_operators_data
  end

  def test_case_operator_ids
    test_case_operator_data.map { |used_operator_data| used_operator_data['operator_id'] }
  end

  delegate :used_operators_data, to: :test_case, prefix: true

  def passed_operators
    @passed_operators ||= test_case_operator_data.select do |used_operator_data|
      used_operators_data.include?(used_operator_data)
    end.map { |used_operator_data| UsedOperator.new(used_operator_data) }
  end

  def failed_operators
    return @failed_operators if defined?(@failed_operators)

    id_to_used_operator_data = used_operators_data.index_by { |used_operator_data| used_operator_data[:operator_id] }
    id_to_test_case_operator_data = test_case_operator_data.index_by do |used_operator_data|
      used_operator_data['operator_id']
    end

    @failed_operators = id_to_used_operator_data.select do |id, used_operator_data|
      used_operator_data != id_to_test_case_operator_data[id]
    end.map do |id, used_operator_data|
      [UsedOperator.new(id_to_test_case_operator_data[id]),
       UsedOperator.new(used_operator_data)]
    end
  end

  def missing_operators
    return @missing_operators if defined?(@missing_operators)

    used_operator_ids = used_operators_data.map { |used_operator_data| used_operator_data[:operator_id] }
    @missing_operators = test_case_operator_data.select do |used_operator_data|
      used_operator_ids.exclude?(used_operator_data['operator_id'])
    end.map { |used_operator_data| UsedOperator.new(used_operator_data) }
  end

  def all_operators
    passed_operators + failed_operators.flatten + missing_operators
  end

  def correct_ratio
    ((passed_operators.count.to_f + (failed_operators.count * 0.5)) / test_case_operator_data.count * 100).round(2)
  end

  def compute!
    return unless Clear::TestCase.enabled?
    return if has_started?

    FileUtils.mkdir_p(data_folder_path)
    File.write(data_path, { status: COMPUTING }.to_json)
    result = Clears::GetClearImageFromVideo.call(test_case.video, clear_image_path:)
    if result.success?
      clear_image = ClearImage.new(clear_image_path)
      used_operators_data = clear_image.used_operators_data
      language = clear_image.language
      File.write(data_path, { status: PASSED, used_operators_data:, language: }.to_json)
    else
      File.write(data_path, { status: FAILED, error_message: result.failure }.to_json)
    end
  rescue StandardError => e
    File.write(data_path, { status: FAILED, error_message: e.message }.to_json)
  end

  def read_from_file
    return unless has_started?

    @data = JSON.parse(File.read(data_path)).with_indifferent_access
  end

  def data_folder_path
    @data_folder_path ||= test_run.data_folder_path.join(test_case_id.to_s)
  end

  def data_path
    @data_path ||= data_folder_path.join(DATA_FILENAME)
  end

  def clear_image_path
    @clear_image_path ||= data_folder_path.join('clear.jpg')
  end

  def test_case
    return nil unless test_case_id

    @test_case ||= Clear::TestCase.find_by(id: test_case_id)
  end

  def test_run
    return super if super
    return unless test_run_id

    @test_run ||= Clear::TestRun.find_by(id: test_run_id)
  end

  def destroy_data_folder
    FileUtils.rm_rf(data_folder_path)
  end

  def current_test_case_index
    @current_test_case_index ||= test_run.test_case_ids.find_index(test_case_id)
  end

  def next_result_test_case_id
    next_index = (current_test_case_index + 1)
    return nil if next_index >= test_run.test_case_ids.count

    test_run.test_case_ids[next_index]
  end

  def prev_result_test_case_id
    prev_index = (current_test_case_index - 1)
    return nil if prev_index < 0

    test_run.test_case_ids[prev_index]
  end

  def artifact_image_srcs
    Dir[data_folder_path.join('*.png')].map do |file_path|
      file_path.gsub(Rails.public_path.to_s, '')
    end.reject { |path| path.include?(ClearImage::Logger::NAME_BOX) }
  end

  def name_box_image_srcs
    Dir[data_folder_path.join("#{ClearImage::Logger::NAME_BOX}_*.png")].map do |file_path|
      file_path.gsub(Rails.public_path.to_s, '')
    end
  end

  def clear_image_src
    clear_image_path.to_s.gsub(Rails.public_path.to_s, '')
  end

  delegate :latest_test_runs, to: :test_run

  def latest_test_results
    @latest_test_results ||= latest_test_runs.filter_map { |test_run| test_run.get_test_result(test_case) }
  end

  def max_latest_correct_ratio
    return @max_latest_correct_ratio if @max_latest_correct_ratio

    latest_ratios = latest_test_results.map(&:correct_ratio)
    ap({ "#{test_case_id}" => latest_ratios })
    @max_latest_correct_ratio = latest_ratios.max
  end
end

app/models/clear/test_run.rb
# frozen_string_literal: true

class Clear::TestRun < ApplicationRecord
  self.table_name = 'clear_test_runs'

  STATUSES = [
    STARTED = :started,
    FINISHED = :finished
  ]

  attr_reader :test_count

  attribute :all, :boolean, default: true

  def test_cases
    @test_cases ||= Clear::TestCase.where(id: test_case_ids)
  end

  def test_count=(value)
    @test_count = value.to_i
    return unless value

    self.test_case_ids = Clear::TestCase.take(@test_count).pluck(:id)
  end

  def data_folder_path
    @data_folder_path ||= Rails.public_path.join('tmp', 'clear_test_runs', id.to_s)
  end

  def started?
    data.present?
  end

  def finished?
    data[:status].present?
  end

  def start!
    data[:status] = STARTED
    save!
  end

  def data
    super || {}
  end

  def finish!
    data[:success_count] = test_results.count(&:passed?)
    data[:failed_count] = test_results.count(&:failed?)
    data[:status] = FINISHED
    save!
  end

  def test_case_ids
    super || (@all_test_case_ids ||= Clear::TestCase.pluck(:id))
  end

  def test_results
    @test_results ||= test_case_ids.map do |test_case_id|
      test_result = Clear::TestResult.new(test_case_id:, test_run: self)
      test_result
    end
  end

  def get_test_result(test_case_or_id)
    test_case_id = test_case_or_id.id if test_case_or_id.is_a?(Clear::TestCase)
    result = test_results.find do |test_result|
      test_result.test_case_id == test_case_id
    end
    result.test_case = test_case_or_id if result && test_case_or_id.is_a?(Clear::TestCase)
    result
  end

  def latest_test_runs
    @latest_test_runs ||= Clear::TestRun.where.not(id:).order(id: :desc).limit(5).to_a
  end
end

app/models/concerns/clear/hard_taggable.rb
# frozen_string_literal: true

module Clear::HardTaggable
  include Dry::Monads::Do.for(:add_hard_tags, :remove_hard_tags) # use for all methods make factory bot fail
  extend ActiveSupport::Concern

  included do
    acts_as_taggable_on :hard_tags
  end

  def add_hard_tags(hard_tags)
    new_hard_tag_list = yield hard_tag_list_wrapper.add_tags(hard_tags)
    self.hard_tag_list = new_hard_tag_list
    Success()
  end

  def remove_hard_tags(hard_tags)
    new_hard_tag_list = yield hard_tag_list_wrapper.remove_tags(hard_tags)
    self.hard_tag_list = new_hard_tag_list
    Success()
  end

  private

  def hard_tag_list_wrapper
    Clear::HardTagList.new(hard_tag_list)
  end
end

app/controllers/clears/filters_controller.rb
# frozen_string_literal: true

class Clears::FiltersController < ApplicationController
  skip_before_action :authenticate!
  include ClearFilterable

  def show
    set_clear_spec
  end
end

app/controllers/clears/from_jobs_controller.rb
module Clears
  class FromJobsController < ApplicationController
    include ClearFilterable
    def new
      @job = ExtractClearDataFromVideoJob.find_by(id: params[:job_id])
      return redirect_to(new_clear_path) unless @job.completed?

      set_modifying_clear
      @clear = @job.clear
      clear_spec_session['used_operators_attributes'] = {}
      @clear.used_operators.each_with_index do |used_operator, index|
        clear_spec_session['used_operators_attributes'][index.to_s] = used_operator.attributes.slice(
          'operator_id', 'level', 'elite', 'skill'
        )
      end
      render 'clears/new'
    end
  end
end

app/controllers/clears/likes_controller.rb
class Clears::LikesController < ApplicationController
  authorize_resource class: false

  def create
    @clear = Clear.find(params[:clear_id])
    Current.user.like(@clear)

    respond_to do |format|
      format.html { redirect_to @clear }
      format.turbo_stream
    end
  end

  def destroy
    @clear = Clear.find(params[:clear_id])
    Current.user.unlike(@clear)

    respond_to do |format|
      format.html { redirect_to @clear }
      format.turbo_stream { render :create }
    end
  end
end

app/controllers/clears/operators_selects_controller.rb
class Clears::OperatorsSelectsController < ApplicationController
  skip_before_action :authenticate!
  include ClearFilterable

  def show
    clear_spec_session.merge!(clear_params)
    set_clear_spec
  end
end

app/controllers/clears/reports_controller.rb
class Clears::ReportsController < ApplicationController
  load_and_authorize_resource :clear
  authorize_resource :report, class: false

  def create
    if Current.user.report(@clear)
      respond_to do |format|
        format.html { redirect_to @clear, notice: t('.success') }
        format.turbo_stream { flash.now[:notice] = t('.success') }
      end
    else
      redirect_to @clear, alert: t('.failed')
    end
  end

  def destroy
    if Current.user.unreport(@clear)
      respond_to do |format|
        format.html { redirect_to @clear, notice: t('.success') }
        format.turbo_stream do
          flash.now[:notice] = t('.success')
          render :create
        end
      end
    else
      redirect_to @clear, alert: t('.failed')
    end
  end
end

app/controllers/clears/stage_selects_controller.rb
#  frozen_string_literal: true

class Clears::StageSelectsController < ApplicationController
  skip_before_action :authenticate!
  include ClearFilterable

  def show
    clear_spec_session.merge!(clear_params)
    set_clear_spec
    reset_stage_spec_if_needed
  end
end

app/views/clears/verifications/_accept_btn.html.erb
<%= content_tag :input, nil, id: "verification_form__accept_btn", type: :submit, name: :commit, value: t(:accept), class: 'btn btn-primary', form: 'verification_form', disabled: !@verification.acceptable?,
  data: { turbo_frame: '_top' } %>

app/views/clears/verifications/_reject_btn.html.erb
<%= content_tag :input, nil, id: "verification_form__reject_btn", type: :submit, name: :commit, value: t(:reject), class: 'btn btn-error', form: 'verification_form', disabled: !@verification.rejectable?,
  data: { turbo_frame: '_top', **stimulus(:update_attribute, actions: { click: 'setAttr' }, params: { target_css: '#verification_status', name: 'value', value: Verification::REJECTED })} %>

app/views/clears/verifications/_used_operator.erb
<%= link_to edit_clear_verification_used_operator_path(used_operator.clear, used_operator),
  id: dom_id(used_operator),
  class: "cursor-pointer #{}",
  aria: { label: t('clears.verifications.used_operators.view_details', operator: used_operator.name) },
  data: { turbo_stream: true } do %>
  <%= render Clears::UsedOperatorMiniComponent.new(used_operator: used_operator, show_verification_status: true) %>
<% end %>

app/views/clears/verifications/_used_operator.html.erb
<%= link_to edit_clear_verification_used_operator_path(used_operator.clear, used_operator),
  id: dom_id(used_operator),
  class: "cursor-pointer #{}",
  aria: { label: t('clears.verifications.used_operators.view_details', operator: used_operator.name) },
  data: { turbo_stream: true } do %>
  <%= render Clears::UsedOperatorMiniComponent.new(used_operator: used_operator, show_verification_status: true, class: '') %>
<% end %>

app/views/clears/verifications/create.turbo_stream.erb
<%= turbo_stream.replace dom_id(@clear, :verification) do %>
  <%= render Clears::VerificationComponent.new(clear: @clear) %>
<% end %>
<%= turbo_stream.replace dom_id(@clear, :verification_details) do %>
  <%= render Clears::VerificationDetailsComponent.new(clear: @clear) %>
<% end %>

app/views/clears/verifications/new.html.erb
<% noindex %>
<%= turbo_frame_tag 'clear_verification' do %>
  <section class="card">
    <h2 class="card-title"><%= title t('meta.verifications.new.title') %></h2>
    <div class="card-body space-y-4 !p-2 xs:!p-8">
      <!--flex flex-col lg:flex-row lg:space-x-8 space-y-8 lg:space-y-0-->
      <div class="2xl:flex lg:space-y-0">
        <div class="relative flex-grow">
          <% if (prev_unverified_clear = @clear.prev_unverified) %>
            <%= link_to new_clear_verification_path(prev_unverified_clear), data: { turbo_action: 'advance' },
            class: 'btn btn-sm sm:btn-md  btn-outline btn-circle absolute z-10 -left-[8%] 2xl:-left-12 xl:-left-16 bottom-0 2xl:top-[50%]',
            aria: { label: t(:prev) } do %>
              <%= heroicon 'arrow-left' %>
            <% end %>
          <% end %>
          <% if (next_unverified_clear = @clear.next_unverified) %>
            <%= link_to new_clear_verification_path(next_unverified_clear), data: { turbo_action: 'advance' },
            class: 'btn btn-sm sm:btn-md  btn-outline btn-circle absolute z-10 -right-[8%] 2xl:-right-[40%] xl:-right-[30%] bottom-0 2xl:top-[50%]',
            aria: { label: t(:next) } do %>
              <%= heroicon 'arrow-right' %>
            <% end %>
          <% end %>
          <div class="iframe-responsive-container !w-auto ">
            <iframe src="<%= @clear.embed_link %>" class="iframe-responsive" ></iframe>
          </div>
        </div>
        <section class="card bg-base-200 mt-2 2xl:mt-0 2xl:w-1/5">
          <div class="card-body">
            <h3 class="card-title"><%= t(:squad) %></h3>
            <div class=" grid gap-x-2 gap-y-4 grid-cols-3 sm:grid-cols-7 lg:gap-2 xl:flex xl:gap-2 2xl:grid 2xl:grid-cols-2 2xl:gap-2">
              <%= render partial: 'used_operator', collection: @used_operators %>
            </div>
          </div>
        </section>
      </div>
      <%= simple_form_for @verification, url: clear_verification_path(@clear), html: { id: 'verification_form', class: '!mt-0' } do |f| %>
        <%= f.input :status, as: :hidden, input_html: { value: Verification::ACCEPTED }  %>
        <div class="flex justify-between">
          <% if @clear.verification.persisted? || !(reports_count = @clear.reports_count).zero? %>
            <div class="flex space-x-1 items-center">
              <%= render Clears::VerificationDetailsComponent.new(clear: @clear) %>
              <% unless (reports_count = @clear.reports_count).zero? %>
                <div class="flex w-fit py-1 px-2 rounded text-warning tooltip"
                  data-tip="<%= t('.reports_count', count: reports_count) %>"
                  aria-description="<%= t('.reports_count', count: reports_count) %>"
                >
                  <%= heroicon 'flag', options: { alt: t('.flag') } %>
                </div>
              <% end %>
            </div>
          <% end %>
          <%= link_to t('.go_to_clear'), clear_path(@clear), class: 'btn btn-outline btn-sm', data: { turbo_frame: '_top' } %>
        </div>
        <% if (channel = @clear.channel).present? %>
          <div class="mt-4">
            <div class="flex flex-row items-center">
              <%= link_to channel_path(channel), data: { turbo_frame: '_top' } do %>
                <%= render Channels::AvatarComponent.new(thumbnail_url: channel.thumbnail_url, size_class: 'w-10 h-10 sm:w-12 sm:h-12') %>
              <% end %>
              <div>
                <h3 class="text-base font-semibold"><%= channel.title %></h3>
              </div>
            </div>
          </div>
        <% end %>
        <div class='label'>
          <%= t(:stage) %>
        </div>
        <div class="flex font-bold items-center gap-2 pl-1 text-xl">
          <%= render Stages::CodeComponent.new(stage: @clear.stage, class: "h-6")  %>
        </div>
        <%= f.label :comment, class: 'label' %>
        <div id="verification_from__used_operator_fields">
          <%= f.simple_fields_for :used_operator_verifications do |uovf| %>
            <%= uovf.input_field :status, as: :hidden %>
            <%= uovf.input_field :used_operator_id, as: :hidden %>
          <% end %>
        </div>
        <%= f.input_field :comment, as: :text, placeholder: t(".comment_placeholder"), class: 'w-full placeholder:opacity-50 textarea', maxlength: 1000 %>
      <% end %>
      <footer class="flex justify-between">
        <%= render 'reject_btn', locals: { verification: @verification } %>
        <div class="grid grid-cols-2 gap-2">
          <div></div>
          <%= render 'accept_btn', locals: { verification: @verification } %>
        </div>
      </footer>
    </div>
  </section>
<% end %>